# Generated by Django 2.0.4 on 2018-04-16 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transferencia',
            options={'managed': True},
        ),
    ]
