# Generated by Django 2.0.4 on 2018-04-16 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180416_1010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transferencia',
            options={'managed': False},
        ),
    ]
